language:
 - java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
before_install:
  - pyenv install 3.6
  - pyenv global 3.6
install:
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - ./setup_aws_cli.sh || travis_terminate 1
  - pip install --upgrade pre-commit awsebcli
stages:
  - name: test
  - name: deploy-scipooldev
    if: type = push AND branch = develop
  - name: deploy-scipoolprod
    if: type = push AND branch = prod
jobs:
  include:
    - stage: test
      script:
        - mvn clean test
    - stage: deploy-scipooldev
      script:
        - mvn clean package
        - eb deploy synapse-login-scipooldev --profile default --region us-east-1 --verbose
    - stage: deploy-scipoolprod
      script:
        - mvn clean package
        - eb deploy synapse-login-scipoolprod --profile default --region us-east-1 --verbose
