dist: focal
language: java
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache/pip
branches:
  only:
    - develop
    - prod
env:
  global:
    - REPO_NAME="${PWD##*/}"
    - AWS_REGION="us-east-1"
install:
  # install awscli v2
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip && sudo ./aws/install
  # install other tools
  - pip install travis-wait-improved awsebcli
before_script:
  # Setup AWS CLI profile for multiple AWS accounts
  - mkdir -p ~/.aws
  - echo -e "[profile develop]\nsource_profile=ci-user-develop\nrole_arn=${AwsCfServiceRoleArn_develop}\n" > ~/.aws/config
  - echo -e "[ci-user-develop]\naws_access_key_id=${AwsTravisAccessKey_develop}\naws_secret_access_key=${AwsTravisSecretAccessKey_develop}\n" > ~/.aws/credentials
  - echo -e "[profile prod]\nsource_profile=ci-user-prod\nrole_arn=${AwsCfServiceRoleArn_prod}\n" >> ~/.aws/config
  - echo -e "[ci-user-prod]\naws_access_key_id=${AwsTravisAccessKey_prod}\naws_secret_access_key=${AwsTravisSecretAccessKey_prod}\n" >> ~/.aws/credentials
  - echo -e "[profile strides]\nsource_profile=ci-user-strides\nrole_arn=${AwsCfServiceRoleArn_strides}\n" >> ~/.aws/config
  - echo -e "[ci-user-strides]\naws_access_key_id=${AwsTravisAccessKey_strides}\naws_secret_access_key=${AwsTravisSecretAccessKey_strides}\n" >> ~/.aws/credentials
  - echo -e "[profile bmgfki]\nsource_profile=ci-user-bmgfki\nrole_arn=${AwsCfServiceRoleArn_bmgfki}\n" >> ~/.aws/config
  - echo -e "[ci-user-bmgfki]\naws_access_key_id=${AwsTravisAccessKey_bmgfki}\naws_secret_access_key=${AwsTravisSecretAccessKey_bmgfki}\n" >> ~/.aws/credentials
stages:
  - name: test
  - name: eb-deploy-scipooldev
  - name: eb-deploy-scipoolprod
  - name: eb-deploy-strides
  - name: eb-deploy-bmgfki
jobs:
  fast_finish: true
  include:
    - stage: test
      script: mvn clean package
    - stage: eb-deploy-scipooldev
      if: (NOT type IN (pull_request)) AND (branch = develop)
      script:
        - mvn clean package
        - eb deploy --profile develop --verbose --region ${AWS_REGION} --staged --timeout 30 synapse-login-scipooldev
    - stage: eb-deploy-scipoolprod
      if: (NOT type IN (pull_request)) AND (branch = prod)
      script:
        - mvn clean package
        - eb deploy --profile prod --verbose --region ${AWS_REGION} --staged --timeout 30 synapse-login-scipoolprod
    - stage: eb-deploy-strides
      if: (NOT type IN (pull_request)) AND (branch = prod)
      script:
        - mvn clean package
        - eb deploy --profile strides --verbose --region ${AWS_REGION} --staged --timeout 30 synapse-login-strides
    - stage: eb-deploy-bmgfki
      if: (NOT type IN (pull_request)) AND (branch = prod)
      script:
        - mvn clean package
        - eb deploy --profile bmgfki --verbose --region ${AWS_REGION} --staged --timeout 30 synapse-login-bmgfki
