language:
 - java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
before_install:
  - pyenv install 3.6.3
  - pyenv global 3.6.3
install:
  - wget https://github.com/Sage-Bionetworks/infra-utils/archive/master.zip -O /tmp/infra-utils.zip
  - unzip -j -n /tmp/infra-utils.zip -x "infra-utils-master/.gitignore" "infra-utils-master/LICENSE" "infra-utils-master/*.md" "infra-utils-master/aws/*"
  - ./setup_aws_cli.sh || travis_terminate 1
  - pip install --upgrade pre-commit awsebcli
stages:
  - name: test
  - name: deploy
    if: type = push AND (branch = develop OR branch = prod OR branch = strides)

# map deployment target to beanstalk environment defined in .elasticbeanstalk/config.yaml
before_script: |
  if [ $TRAVIS_BRANCH == 'develop' ]
  then
    export BEANSTALK_ENV="synapse-login-scipooldev"
  then
  elif [ $TRAVIS_BRANCH == 'prod' ]
    export BEANSTALK_ENV="synapse-login-scipoolprod"
  then
  elif [ $TRAVIS_BRANCH == 'strides' ]
  then
    export BEANSTALK_ENV="synapse-login-strides"
  fi
jobs:
  include:
    - stage: test
      script:
        - mvn clean package
    - stage: deploy
      script:
        - mvn clean package
        - eb deploy $BEANSTALK_ENV --profile default --region us-east-1 --verbose
