language:
 - java
jdk:
  - openjdk8
cache:
  directories:
  - $HOME/.m2
before_install:
  - pyenv global 3.7.1
  - pip install --upgrade pip
install:
  - pip install pre-commit travis-wait-improved awsebcli~=3.19
stages:
  - name: test
  - name: deploy-develop
    if: type = push AND branch = develop
  - name: deploy-prod
    if: type = push AND branch = prod
jobs:
  include:
    - stage: test
      script:
        - mvn clean package
    - stage: deploy-develop
      name: "org-sagebase-scipooldev"
      script:
        - mkdir -p ~/.aws
        - echo -e "[default]\nregion=us-east-1\nsource_profile=default\nrole_arn=$AwsCfServiceRoleArn_develop" > ~/.aws/config
        - echo -e "[default]\nregion=us-east-1\naws_access_key_id=$AwsTravisAccessKey_develop\naws_secret_access_key=$AwsTravisSecretAccessKey_develop" > ~/.aws/credentials
        - mvn clean package
        - travis-wait-improved --timeout 30m eb deploy synapse-login-scipooldev --profile default --region us-east-1 --verbose
    - stage: deploy-prod
      name: "org-sagebase-scipoolprod"
      script:
        - mkdir -p ~/.aws
        - echo -e "[default]\nregion=us-east-1\nsource_profile=default\nrole_arn=$AwsCfServiceRoleArn_prod" > ~/.aws/config
        - echo -e "[default]\nregion=us-east-1\naws_access_key_id=$AwsTravisAccessKey_prod\naws_secret_access_key=$AwsTravisSecretAccessKey_prod" > ~/.aws/credentials
        - mvn clean package
        - travis-wait-improved --timeout 30m eb deploy synapse-login-scipoolprod --profile default --region us-east-1 --verbose
    - stage: deploy-prod
      name: "org-sagebase-strides"
      script:
        - mkdir -p ~/.aws
        - echo -e "[default]\nregion=us-east-1\nsource_profile=default\nrole_arn=$AwsCfServiceRoleArn_strides" > ~/.aws/config
        - echo -e "[default]\nregion=us-east-1\naws_access_key_id=$AwsTravisAccessKey_strides\naws_secret_access_key=$AwsTravisSecretAccessKey_strides" > ~/.aws/credentials
        - mvn clean package
        - travis-wait-improved --timeout 30m eb deploy synapse-login-strides --profile default --region us-east-1 --verbose
    - stage: deploy-prod
      name: "org-sagebase-bmgfki"
      script:
        - mkdir -p ~/.aws
        - echo -e "[default]\nregion=us-east-1\nsource_profile=default\nrole_arn=$AwsCfServiceRoleArn_bmgfki" > ~/.aws/config
        - echo -e "[default]\nregion=us-east-1\naws_access_key_id=$AwsTravisAccessKey_bmgfki\naws_secret_access_key=$AwsTravisSecretAccessKey_bmgfki" > ~/.aws/credentials
        - mvn clean package
        - travis-wait-improved --timeout 30m eb deploy synapse-login-bmgfki --profile default --region us-east-1 --verbose
