branch-defaults:
  develop:
    environment: synapse-login-scipooldev
  prod:
    environment: synapse-login-scipoolprod
  strides:
    environment: synapse-login-strides
global:
  application_name: synapse-login
  workspace_type: Application
deploy:
  artifact: target/SynapseAWSConsoleLogin-1.0.war
