# reusable template for running Elastic Beanstalk deployments to AWS accounts
name: aws-deploy

on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        default: us-east-1
      role-to-assume:
        required: true
        type: string
      role-duration-seconds:
        type: number
        default: 1800
      ebcli-command:
        required: true
        type: string

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: GHA-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: ${{ inputs.role-duration-seconds }}
      # install specific version of python and EBCLI as a workaround for https://github.com/aws/aws-elastic-beanstalk-cli-setup/issues/148
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install EB CLI
        uses: sparkplug-app/install-eb-cli-action@v1.1.1
        with:
          version: 3.19.4
      - name: Deploy to Beanstalk
        run: ${{ inputs.ebcli-command }}
