name: main

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sparkplug-app/install-eb-cli-action@v1.1.0
